#ifndef __RS_polynomial
#define __RS_polynomial

#include "my_hhash.h"
#include "merkle_tree.h"
#include "fieldElement.hpp"
#include <cassert>
#include "constants.h"

namespace virgo {
    void init_scratch_pad(int order);

//Given coefficient of polynomials, output the evaluations on the group generated by root of unity(RoT) [RoT^i for i in range(order)]
    void fast_fourier_transform(const fieldElement *coefficients, int coef_len, int order, fieldElement root_of_unity,
                                fieldElement *result);


//see https://codeforces.com/blog/entry/48798 for tutorial
    void inverse_fast_fourier_transform(fieldElement *evaluations, int coef_len, int order, fieldElement root_of_unity,
                                        fieldElement *result);
}
#endif